sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: gaosen123
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t76316BMTuMYGowL3zz
    access-key-secret: IwBqSiUMGPjvdMi7ttVIrVJ0eDKOu6
    bucket-name: kyrie-gson